version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: 8080
        restart: always
        ports:
            - "8080:80"
        environment:
          - CLIENT_PORT=8080
          - SERVER_PORT=3000
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: 3000
        restart: always
        ports:
            - "3000:3000"
        environment:
          SERVER_PORT: 3000

    postgres:
      image: postgres:14     
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: 'supersecret'
        POSTGRES_USER: 'postgres'
        POSTGRES_DB: 'mydb'
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data

