name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      CLIENT_PORT: 8080
      SERVER_PORT: 3000
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
            ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package-lock.json') }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push client Docker image
        run: |
          docker-compose build --build-arg CLIENT_PORT=${CLIENT_PORT} --build-arg SERVER_PORT=${SERVER_PORT} --build-arg POSTGRES_PORT=${POSTGRES_PORT} --build-arg POSTGRES_PASSWORD=${POSTGRES_PASSWORD} --build-arg POSTGRES_USER=${POSTGRES_USER} --build-arg POSTGRES_DB=${POSTGRES_DB} --build-arg GITHUB_SHA=${{ github.sha }} -t ghcr.io/${{ github.repository_owner }}/prakticum-client:${{ github.sha }} prakticum-client
          docker-compose push ghcr.io/${{ github.repository_owner }}/prakticum-client:${{ github.sha }}
      - name: Build and push server Docker image
        run: |
          docker-compose build --build-arg CLIENT_PORT=${CLIENT_PORT} --build-arg SERVER_PORT=${SERVER_PORT} --build-arg POSTGRES_PORT=${POSTGRES_PORT} --build-arg POSTGRES_PASSWORD=${POSTGRES_PASSWORD} --build-arg POSTGRES_USER=${POSTGRES_USER} --build-arg POSTGRES_DB=${POSTGRES_DB} --build-arg GITHUB_SHA=${{ github.sha }} -t ghcr.io/${{ github.repository_owner }}/prakticum-server:${{ github.sha }} prakticum-server
          docker-compose push ghcr.io/${{ github.repository_owner }}/prakticum-server:${{ github.sha }}
