name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      CLIENT_PORT: 8080
      SERVER_PORT: 3000
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$GITHUB_SHA
          build-args: |
            CLIENT_PORT=${CLIENT_PORT}
            SERVER_PORT=${SERVER_PORT}
            POSTGRES_PORT=${POSTGRES_PORT}
            POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            POSTGRES_USER=${POSTGRES_USER}
            POSTGRES_DB=${POSTGRES_DB}
